### ISSUE TITLE
Buttons on status bar not working

### ISSUE THREAD

**Issue by DPDmancul** [neutronka/hunspell-spellchecker#3]
In Linux Kubuntu 16.04 with VSCode 1.14.0 and hunspell-spellchecker 1.0.1 the buttons in the status bar for switching language and on/off don't work: when I click on them nothing appends.

**Comment by DPDmancul** [comment]
After a few minutes an error message came out:
`[Extension Host] spellchecking: 0.099ms
/snap/vscode/13/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 Extension Host
/snap/vscode/13/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/snap/vscode/13/usr/share/code/libnode.so]
 2: 0x7f213ca901b7 [/snap/vscode/13/usr/share/code/libnode.so]
 3: 0x7f213c7eba87 [/snap/vscode/13/usr/share/code/libnode.so]
 4: 0x7f213c7eba05 [/snap/vscode/13/usr/share/code/libnode.so]
 5: v8::internal::Factory::NewInternalizedStringImpl(v8::internal::Handle<v8::internal::String>, int, unsigned int) [/snap/vscode/13/usr/share/code/libnode.so]
 6: 0x7f213c436ef8 [/snap/vscode/13/usr/share/code/libnode.so]
 7: 0x7f213c429d2b [/snap/vscode/13/usr/share/code/libnode.so]
 8: v8::internal::StringTable::LookupString(v8::internal::Isolate*, v8::internal::Handle<v8::internal::String>) [/snap/vscode/13/usr/share/code/libnode.so]
 9: 0x7f213c54a3ce [/snap/vscode/13/usr/share/code/libnode.so]
10: 0x34e2826043a7

<--- Last few GCs --->

[6429:0x271ff82e3000]   119576 ms: Mark-sweep 1400.3 (1452.4) -> 1400.3 (1421.4) MB, 4482.2 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 4482 ms) last resort 
[6429:0x271ff82e3000]   124168 ms: Mark-sweep 1400.3 (1421.4) -> 1400.3 (1421.4) MB, 4592.5 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x16526127831 <JS Object>
    1: hasOwnProperty(this=0x15bc4b4beb91 <an Object with map 0x23dee5efd721>,0x249ae177e661 <String[18]: bell'Asciughiamovi>)
    2: parse(aka parse) [/home/dpd-/.vscode/extensions/denisgerguri.hunspell-spellchecker-1.0.1/node_modules/nspell/lib/util/dictionary.js:~16] [pc=0x34e282973991](this=0x27fb1e602311 <undefined>,buf=0x27fb1e602311 <undefined>,options=0x27fb1e602311 <undefined>,dict=0x27...


index.js:5 [uncaught exception]: Error: read ECONNRESET
onError @ index.js:5
index.js:5 Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at Pipe.onread (net.js:572:26)
onError @ index.js:5
events.js:160 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at Pipe.onread (net.js:572:26)
/snap/vscode/13/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28 L'host dell'estensione è stato terminato in modo imprevisto. Ricaricare la finestra per ripristinare.
e.doShow @ /snap/vscode/13/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:28
/snap/vscode/13/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 Extension host terminated unexpectedly. Code:  null  Signal:  SIGABRT
h.onExit @ /snap/vscode/13/usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29`

**Comment by SkaceKamen** [comment]
It looks like the extension is just really slow. It takes like 60 seconds to load new dictionary, the extension is unresponsive while doing so which could cause issues with extension communication..
